version: '3.11'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: test_db
    environment:
      - MONGO_INITDB_DATABASE=sampleDB
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6:
